# Generated by Django 4.2.1 on 2023-05-23 15:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(auto_now_add=True)),
                (
                    "expected_return_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=django.db.models.expressions.CombinedExpression(
                                    models.F("borrow_date"),
                                    "+",
                                    models.Value(datetime.timedelta(days=1)),
                                )
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=django.db.models.expressions.CombinedExpression(
                                    models.F("borrow_date"),
                                    "+",
                                    models.Value(datetime.timedelta(days=30)),
                                )
                            ),
                        ]
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
