# Generated by Django 4.2.1 on 2023-05-23 16:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 5, 24)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 6, 22)
                    ),
                ]
            ),
        ),
    ]
